#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <conio.h>
#include <ctype.h>
#include "socios.h"
#include "prestamos.h"
#include "input.h"
#include "fechas.h"
#include "autores.h"
